###Home
GET http://localhost:3000/

### GET USERS
GET http://localhost:3000/users

###GET USERS by Option
GET http://localhost:3000/users?option=DesireOpion 

### GET USER by name
GET http://localhost:3000/users/dy

### POST USER
POST http://localhost:3000/users
Content-Type: application/json

{   
    "name": "dy",
    "email":"dy@gmail.com",
    "password": "dy123456"
}

### DELETE USER
DELETE http://localhost:3000/users/dyla

### PUT USER
PUT http://localhost:3000/users/dylalu
Content-Type: application/json

{   
    "name": "dy",
    "email":"dy@gmail.com",
    "password": "dy123456"
}

###QUESTIONS
GET http://localhost:3000/questions

###ANSWERS
GET http://localhost:3000/answers

###FLASHBACKS
GET http://localhost:3000/flashbacks