###Home
GET http://localhost:4000/

### GET USERS
GET http://localhost:4000/users

### GET USER by name
GET http://localhost:4000/users/herav

### POST USER
POST http://localhost:4000/users
Content-Type: application/json

{   
    "name": "vic",
    "email":"vic@gmail.com",
    "password": "vic123456"
}

### DELETE USER
DELETE http://localhost:4000/users/herav

### PUT USER
PUT http://localhost:4000/users/vic
Content-Type: application/json

{   
    "name": "herav",
    "email":"herav@gmail.com",
    "password": "herav123456"
}

###GET USERS by Option
GET http://localhost:4000/users?option=DesireOpion 

###QUESTIONS
GET http://localhost:4000/questions

###ANSWERS
GET http://localhost:4000/answers

###FLASHBACKS
GET http://localhost:4000/flashbacks