export const getUsersQuery = "SELECT id,name,email,password FROM users"
export const getUserQuery = "SELECT * FROM users WHERE name = $1"
export const getUserByIDQuery = "SELECT * FROM users WHERE id = $1"
export const uuidQuery = "SELECT gen_random_uuid()"
export const postUserQuery = "INSERT INTO users (id,name,email,password) VALUES ($1,$2,$3,$4)"
export const deleteUserQuery = "DELETE FROM users where name = $1"
export const putUserQuery = "UPDATE users SET name = $1, email = $2, password = $3 WHERE name = $4"
